[package]
name = "downmix"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
serde = "1.0.189"
serde_json = "1.0.107"
tracing = "0.1.39"
tracing-subscriber = "0.3.17"
